<?php 

$_item = $block->getItem();
$product = $_item->getProduct(); // Get cart product details
$additional_data = $block->getAdditionalData(); // Get cart product additionl details defined in block page
foreach ($additional_data as $add_data => $value_key){

if(($add_data == $product->getId()) && ($value_key == '1') && ($value_key != '')){
?>
<div class="Title"><strong><?php echo "(Contains Alcohol)"; ?></strong></div>
<?php 
  } 
 }
?>

