<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();

/*****************image url for media folder****/
$imageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'custom_banner/banner' ;

/*****************image name from media folder****/
$image =  $store->getConfig('section_custombanner/group_custombanner/upload_image_id');

/****************category custom attribute value from catalgue/category in admin enable,disable***/

$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category'); //get current category
       /* echo $category->getId();
        echo $category->getName();*/
    if($category !=''){   
      $categoryId = $category->getId();
      $banner_enable= $category->getData('custom_banner_enable');
    }else{
     $banner_enable="home";
    }
   #echo '<pre>';print_r($category->getData('custom_banner_enable'));exit;
 
 if(($banner_enable == 1)||($banner_enable=='home')){
?>

 <center><img src="<?php echo $block->getStoreInterface($image) ?>" alt="banner_image" width="1250 px" style="height: 300px !important"/></center>


<?php  } ?>