<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();

$getstatesOptions =  $store->getConfig('states_section/group_customstates/states_required');

//2,4,6,8,12,13,14,15,19,26,27,28,54,55,56,57,58,60
    $states = array();

    $mystates = explode(",",$getstatesOptions);
    foreach($mystates as $states_id)
    {

     // echo '<pre>';print_r($states_id);exit;
            if($states_id)
            {

               /*$region[] = $objectManager->create('Magento\Directory\Model\ResourceModel\Region\Collection')
                        ->addFieldToFilter('region_id', ['eq' => $states_id])
                        ->getFirstItem();*/
               $region = $objectManager->create('Magento\Directory\Model\Region')
                        ->load($states_id);
                $states[$states_id] =  $region->getName();
            }
    }

#echo '<pre>';print_r($states);exit;

#echo '<pre>';print_r($getstatesOptions);exit;

?>

<script type="text/javascript">
  window.valuesConfig = '<?php echo $states; ?>';
</script>