<?php
 $collection = $block->getEditData();          

#echo '<pre>';print_r($regionFactory->getData());exit;
/*****/ 
/****get countries all *************/
/*
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $allowerdContries = $objectManager->get('Magento\Directory\Model\AllowedCountries')->getAllowedCountries() ;
    $countryFactory = $objectManager->get('\Magento\Directory\Model\CountryFactory');
    
    #echo "<pre>"; print_r($allowerdContries);exit;
    
    $countries = array();
    foreach($allowerdContries as $countryCode)
    {
            if($countryCode)
            {

                $data = $countryFactory->create()->loadByCode($countryCode);
                $countries[$countryCode] =  $data->getName();
            }
    }
*/
 /*****/ 

 /****get only us states all *************/
/*$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$regionFactory = $objectManager->create('Magento\Directory\Model\ResourceModel\Region\CollectionFactory')->create();
$regionFactory->addFieldToFilter('country_id', array('eq' => 'US'));*/

$blockObj= $block->getLayout()->createBlock('DCKAP\Frontendmodule\Block\Regions');
$regionFactory = $blockObj->getRegionsOfCountry(); 

?>
<div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
               action="<?php echo $this->getUrl('mymodule/index/save', ['_secure' => true]);?>"
         id="custom-form"
         method="post"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
              <input type="hidden" name="editId" id="editId" value="<?= $collection['id']; ?>" />
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Name')) ?></span></label>
                            <div class="control">
                                <input name="name" id="name" title="Name" value="<?= $collection['name']; ?>" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="email" id="email" title="Email" value="<?= $collection['email']; ?>" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Telephone')) ?></span></label>
                            <div class="control">
                                <input name="telephone" id="telephone" title="Telephone" value="<?= $collection['telephone']; ?>" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>

                         <div class="field name required">
                        <label for="dob" class="label"><span><?php /* @escapeNotVerified */ echo __('Date of birth') ?></span>
                        </label>
                      
                       <input type="text" name="dob" id="dob" value="<?= $collection['dob']; ?>" class="datepicker input-text" data-validate="{required:true}">
                        
                      </div>

                       <div class="no-dob" style="color:red;"></div>

                       <div class="field name required">
                            <label class="label" for="title"><span><?php /* @escapeNotVerified */ echo __('Age') ?></span></label>
                            <div class="control">
                                <input name="age" id="age" title="age" value="<?= $collection['age']; ?>" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="no-age" style="color:red;"></div>

                        <div class="field name required">
                         <label for="country" class="label"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span>
                        </label>
                        
                        <?php if(($regionFactory) != ''){?>
                        <select name="country" id="country" data-validate="{required:true}">
                            <option value="">--- Please select country ---</option>
                            <?php foreach($regionFactory as $states)
                              {
                            ?>
                                <option value="<?php echo $states['label']; ?>" <?php if($collection['country']==$states['label']) echo 'selected="selected"'; ?> ><?php echo $states['label'] ?></option>
                            <?php } ?>
                        </select>
                        <?php } ?>
                   

                  </div>
                  <div class="no-country" style="color:red;"></div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?php  echo __('Submit') ?>" class="action submit primary" id="custom_btn">
                    <span><?php  echo __('Submit') ?></span>
                </button>
            </div>
        </div>
        </form>
    </div>
</div>



<script>
require(["jquery", "mage/calendar"], function($){
        $("#dob").datepicker({
             onSelect: function(value, ui) {
            var today = new Date(),
                dob = new Date(value),
                age = new Date(today - dob).getFullYear() - 1970;

              //  alert(age);

            $('#age').val(age);
        },
          showMonthAfterYear: false,
          dateFormat:'mm/dd/yy',
          changeMonth: true,
          changeYear: true,
          yearRange: '2000:2020',

        })
});
</script>