<?php 

$blockObj= $block->getLayout()->createBlock('DCKAP\AlcoholicModule\Block\Addtocart\Js');
$data_ship = $blockObj->getShippingregion();

 /*  REFERnce code of my
$config = $block->getLayout()->createBlock(\Magento\Config\Block\System\Config\Form::class);
$configValue = $config->getConfigValue('states_section/group_customstates/states_required');
//echo '<pre>';print_r($data);exit;

$getstatesOptions =  $configValue;
    $states = array();

  $mystates = explode(",",$getstatesOptions);
    foreach($mystates as $states_id)
    {
            if($states_id)
            {

               $region[] = $dats->create('Magento\Directory\Model\ResourceModel\Region\Collection')
                        ->addFieldToFilter('region_id', ['eq' => $states_id])
                        ->getFirstItem();
               $region = $dats->create('Magento\Directory\Model\Region')
                        ->load($states_id);
                $states[$states_id] =  $region->getName();
            }
    }*/

#echo '<pre>';print_r($states);exit;

#echo '<pre>';print_r($getstatesOptions);exit;

?>

<div id="modal-content">
    <div class="modal-inner-content">
        <h2>Item has been added to cart.</h2>
        <p>we ship alcoholic products only to these states</p>
        
       <p><?php echo '<ul>';
        foreach ($data_ship as $pitem) {
        echo '<li>'.$pitem.'</li>';
        }
        echo '</ul>'; ?>
            
        </p> 
    </div>
</div>


