<?php 



/*****************image url for media folder****/
/*$getdatass = \Magento\Framework\App\ObjectManager::getInstance();
$store = $getdatass->get('Magento\Store\Model\StoreManagerInterface')->getStore();
$imageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'custom_banner/banner' ;*/

/*****************image name from media folder****/

//$config = $block->getLayout()->createBlock(\Magento\Config\Block\System\Config\Form::class);
//$image = $config->getConfigValue('section_custombanner/group_custombanner/upload_image_id');
//$image =  $store->getConfig('section_custombanner/group_custombanner/upload_image_id');

/****************category custom attribute value from catalgue/category in admin enable,disable***/


$config = $block->getLayout()->createBlock(\Magento\Config\Block\System\Config\Form::class);
$image = $config->getConfigValue('section_custombanner/group_custombanner/upload_image_id');


$blockObj= $block->getLayout()->createBlock('DCKAP\Bannermodule\Block\Current');
$category = $blockObj->getCurrentCategory(); //get current category
       
    if($category !=''){   
      $categoryId = $category->getId();
      $banner_enable= $category->getData('custom_banner_enable');
    }else{
     $banner_enable="home";
    }
   #echo '<pre>';print_r($category->getData('custom_banner_enable'));exit;
 
 if(($banner_enable == 1)||($banner_enable=='home')){
?>

 <center><img src="<?php echo $block->getStoreInterface($image) ?>" alt="banner_image" width="1250 px" style="height: 300px !important"/></center>


<?php  } ?>