<?php
/**
* Copyright © Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
*/

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product_det = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
//echo $product->getId();
$categoryId = $product_det->getId();
$alocholic_enable= $product_det->getData('enable_alcoholic_attribute');

$_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
   <div class="fieldset">
    <?php 
       if(($alocholic_enable == 1)){
       ?>
       <div class="stock available"><span> Note: </span></div>
       <div ><span>Contains Alcohol</span></div>
        <?php } ?>
       <?php if ($block->shouldRenderQuantity()): ?>
       <div class="field qty">
           <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
           <div class="control">
               <input type="number"
                      name="qty"
                      id="qty"
                      value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                      title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                      class="input-text qty"
                      data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                      />
           </div>
           
       </div>
       <?php endif; 
       if(($alocholic_enable == 1)){
       ?>
       <!-- <div class="stock available"><span>Contains Alcohol</span></div> -->
       <div class="actions">
           <button type="submit"
                   title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                   class="action primary newcolor"
                   id="product-addtocart-button">
               <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
           </button>
           <?= $block->getChildHtml('', true) ?>
       </div>
        <?php }else{ ?>

         <div class="actions">
           <button type="submit"
                   title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                   class="action primary newcolor"
                   id="product-addtocart-button-new">
               <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
           </button>
           <?= $block->getChildHtml('', true) ?>
       </div>

        <?php } ?>
   </div>
</div>
<?php endif; ?>

<div id="popup-modal">
<?php include ($block->getTemplateFile("DCKAP_Training::product/view/addtocart.phtml")); ?>
</div>

<div id="popup-modal-normal">
<?php include ($block->getTemplateFile("DCKAP_Training::product/view/addtocart_normal.phtml")); ?>
</div>

<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
   {
       "#product_addtocart_form": {
           "Magento_Catalog/product/view/validation": {
               "radioCheckboxClosest": ".nested"
           }
       }
   }
</script>
<?php else : ?>
<script type="text/x-magento-init">
   {
       "#product_addtocart_form": {
           "Magento_Catalog/js/validate-product": {}
       }
   }
</script>
<?php endif; ?>

<script>
require(
    [
        'jquery',
        'Magento_Ui/js/modal/modal'
    ],
  function(
        $,
        modal
    ) {
        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            buttons: [{
                text: $.mage.__('Continue'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        var popup = modal(options, $('#popup-modal'));
        $("#product-addtocart-button").on('click',function(){
            $("#popup-modal").modal("openModal");
        });

        var popup = modal(options, $('#popup-modal-normal'));
        $("#product-addtocart-button-new").on('click',function(){
            $("#popup-modal-normal").modal("openModal");
        });

    }
);
</script>



  